language: smalltalk
sudo: false

os:
  - linux
  - osx

smalltalk:
  - GemStone-3.1.0.6
  - GemStone-3.2.12
  - GemStone-3.3.0

#matrix:
#  allow_failures:
#    - os: linux   # requires 3.4.0, but let's see how it goes

#script:
#  - ./run.sh --debug
