language: erlang

env:
   - CLIENT=Pharo-1.4 GemStone=GemStone-3.1.0.2
#   - CLIENT=Pharo-1.4 ST=GemStone-2.4.4.1

install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -q -O builderCI.zip https://github.com/dalehenrich/builderCI/zipball/master
   - unzip -q builderCI.zip
   - cd dalehenrich-builderCI*
   - source build_env_vars
   - ln -s $PROJECT_HOME $GIT_PATH
   - export ST="$GemStone"
   - ./build_image.sh
   - export ST="$CLIENT"
   - ./build_image.sh
   - export LD_LIBRARY_PATH="/opt/gemstone/product/lib32"
   - ls -altr /usr/lib32

script: $BUILDER_CI_HOME/testGemStoneGCI.sh # -verbose
