language: erlang

env:
#   - GS_VERSION=2.4.7
#   - GS_VERSION=3.1.0.6
   - GS_VERSION=3.2.12 GS_DEVKIT_HOME_BRANCH=master
   - GS_VERSION=3.2.12 GS_DEVKIT_HOME_BRANCH=dev

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/47796c01bb932d6a0300 # dalehenrich/chat
      - https://webhooks.gitter.im/e/f662b9bc952d22a2f11f # dalehenrich/tode
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

addons:
  hosts:
    - travis.dev

before_script:
  - export BASE="$(pwd)"
  - git clone https://github.com/GsDevKit/GsDevKit_home.git
  - cd GsDevKit_home
  - git checkout $GS_DEVKIT_HOME_BRANCH
  - export GS_HOME="$(pwd)"
  - export PATH=$GS_HOME/bin:$PATH
  - export GS_TRAVIS=true
  - cd $BASE

script:
  - sudo hostname travis.dev
  - $GS_HOME/bin/private/clone_sys_local -c https # pre-clone /sys/local, for travisCustomize.sh
  - tests/travisCustomize.sh             # no backups on travis and use proposed tODE repo
  - installServer
  - createClient tode
  - createStone travis $GS_VERSION
  - tests/installSmalltalkCI.sh travis

    # tODE
  - tests/testTode.sh travis

